builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin

brews:
  - tap:
      owner: Justintime50
      name: homebrew-formulas
    folder: formula
    homepage: 'https://github.com/Justintime50/freedom'
    description: 'Give your computer the freedom to do more'
    commit_author:
      name: Justintime50
      email: justinpaulhammond@gmail.com
